// Mocks generated by Mockito 5.3.2 from annotations
// in speeches/test/features/quotes/data/repositories/quote_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:speeches/features/quotes/data/dataSources/quotes_local_data_source.dart'
    as _i5;
import 'package:speeches/features/quotes/data/dataSources/quotes_remote_data_source.dart'
    as _i2;
import 'package:speeches/features/quotes/data/models/quotes_model.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [QuotesRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteDataSource extends _i1.Mock
    implements _i2.QuotesRemoteDataSource {
  @override
  _i3.Future<List<_i4.QuotesModel>> getRandomQuote() => (super.noSuchMethod(
        Invocation.method(
          #getRandomQuote,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.QuotesModel>>.value(<_i4.QuotesModel>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.QuotesModel>>.value(<_i4.QuotesModel>[]),
      ) as _i3.Future<List<_i4.QuotesModel>>);
}

/// A class which mocks [QuotesLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalDataSource extends _i1.Mock
    implements _i5.QuotesLocalDataSource {}
